config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'cambios#index'
  resources :cambios, only: [:index, :show, :edit, :update]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cambio.rb
class Cambio < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/cambios_controller.rb
class CambiosController < ApplicationController

  skip_before_action :authenticate_user!, only: :index
  before_action :set_cambios, only: [:show, :edit, :update]
  def index
    @cambios = Cambio.all
  end

  def show

  end

  def edit
  end

  def update
    @cambio.update(cambios_params)
    redirect_to root_path
  end

  private

  def cambios_params
    params.require(:cambio).permit(:dolarv, :dolarc, :euroc, :eurov, :realc, :realv, :uruguayo, :uruguayov, :chilenoc, :chilenov, :gbpcompra, :gbpventa)
  end

  def set_cambios
    @cambio = Cambio.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home]

  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cambios/edit.html.erb
<br><br><br><br>
<div class="form-container">
  <h1>Editar</h1>

  <%= simple_form_for @cambio do |f| %>
  <%= f.error_notification %>

  <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1554760381/flag-usa.jpg" alt="">
  <%= f.input :dolarc, label: 'Dolar Compra', required: true, value: @cambio.dolarc %>
  <%= f.input :dolarv, label: 'Dolar Venta', required: true, value: @cambio.dolarv %>
  <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1554760381/flag-euro.jpg" alt="">
  <%= f.input :euroc, label: 'Euro Compra', required: true, value: @cambio.euroc %>
  <%= f.input :eurov, label: 'Euro Venta', required: true, value: @cambio.eurov %>
  <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1554760381/gb.png" alt="">
  <%= f.input :gbpcompra, label: 'Libras Compra', required: true, value: @cambio.gbpcompra %>
  <%= f.input :gbpventa,label: 'Libras Venta', required: true, value: @cambio.gbpventa %>
  <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1554760381/flag-br.jpg" alt="">
  <%= f.input :realc, label: 'Real Compra', required: true, value: @cambio.realc %>
  <%= f.input :realv,label: 'Real Venta', required: true, value: @cambio.realv %>
  <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1554760381/flag-ur.jpg" alt="">
  <%= f.input :uruguayo, label: 'Uruguayo Compra', required: true, value: @cambio.uruguayo %>
  <%= f.input :uruguayov,label: 'Uruguayo Venta', required: true, value: @cambio.uruguayov %>
  <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1559658494/flag-ch.jpg" alt="">
  <%= f.input :chilenoc, label: 'Chileno Compra', required: true, value: @cambio.chilenoc %>
  <%= f.input :chilenov,label: 'Chileno Venta', required: true, value: @cambio.chilenov %>

  <%= f.button :submit, "Actualizar Cambio", class: 'btn btn-primary' %>

  <% end %>

</div>

app/views/cambios/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.1),rgba(0,0,0,0.1)), url(https://res.cloudinary.com/dw7ox75dg/image/upload/v1555105203/Lamebo_0419_Baja-9342.jpg);">
  <div class="banner-container">
    <p>Agencia de Cambio</p>
    <h1>Bienvenidos</h1>
    <h3>
    Estamos ubicados a metros de Callao y Santa Fe, en un elegante local dispuesto para la atención al público. La comodidad y seguridad de nuestros clientes es un  objetivo fundamental de nuestra Empresa.</h3>
  </div>
</div>
<section id= "cotizaciones">
  <div class="description">
    <h1>COTIZACIONES</h1>
    <h3> Panel de divisas <i class="fas fa-sort-down"></i></h3>
    <div class="cotizacion-container">
      <% @cambios.each do |cambio| %>
      <table class="table">
        <thead>
          <tr>
            <th scope="col">Moneda</th>
            <th scope="col"></th>
            <th scope="col">Compra</th>
            <th scope="col">Venta</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td><img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1554760381/flag-usa.jpg" alt=""> <br>Dolar </td>
            <td></td>
            <td>$<%= cambio.dolarc %></td>
            <td>$<%= cambio.dolarv %></td>
          </tr>
          <tr>
            <td><img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1554760381/flag-euro.jpg" alt=""><br>Euros</td>
            <td></td>
            <td>$<%= cambio.euroc %></td>
            <td>$<%= cambio.eurov %></td>
          </tr>
          <tr>
            <td><img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1554760381/gb.png" alt=""><br>Libras</td>
            <td></td>
            <td>$<%= cambio.gbpcompra %> </td>
            <td>$<%= cambio.gbpventa %></td>
          </tr>
          <tr>
           <tr>
            <td><img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1554760381/flag-br.jpg" alt=""><br>Real</td>
            <td></td>
            <td>$<%= cambio.realc %> </td>
            <td>$<%= cambio.realv %></td>
          </tr>
          <tr>
            <td><img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1554760381/flag-ur.jpg" alt=""> <br>Uruguayos </td>
            <td></td>
            <td>$<%= cambio.uruguayo %></td>
            <td>$<%= cambio.uruguayov %></td>
          </tr>
          <tr>
            <td><img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1559658494/flag-ch.jpg" alt=""> <br>Chilenos </td>
            <td></td>
            <td>$<%= cambio.chilenoc %></td>
            <td>$<%= cambio.chilenov %></td>
          </tr>
        </tbody>
      </table>
      <div class="dolar-footer">
        <p>Actualizado: <%= cambio.updated_at.in_time_zone("Buenos Aires").strftime('%d/%m/%y - %H:%M') %> - <%= link_to 'Lamebo',cambio_path(cambio) %> </p>
      </div>
      <% end %>
    </div>
  </div>
</section>
<section id= "quienes">
  <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
      <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
      <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner">
      <div class="carousel-item active">

        <img class="d-block w-100" src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1555515247/Lamebo_0419_Baja-9362.jpg" alt="First slide">
        <div class="carousel-caption">
          <h3>NUESTRA EFICIENCIA, SU SEGURIDAD</h3>
          <p>Nuestros sistema de gestión nos permite atender a clientes locales e internacionales con suma eficiencia. Gracias al registro apropiado de cada transacción , LAMEBO transmite confianza y seguridad a nuestros clientes. Al momento de realizar la compra o venta de moneda extranjera nos caracterizamos por nuestro dinamismo , eficiencia y calidez en la atención al publico.</p>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1558125346/photo-1550565118-3a14e8d0386f.jpg" alt="Second slide">
        <div class="carousel-caption">
          <h3>NUESTRA EMPRESA</h3>
          <p>Somos una Empresa joven y con suficiente experiencia en el mercado cambiario. Nuestra red de operadores cambiarios  nos permite ofrecer un tipo de cambio competitivo para cada moneda que negociamos. Tenemos operadores especializados en materia cambiaria que atienden cada una de las necesidades diarias de nuestros clientes para lograr un alto nivel de satisfacción de los mismos.
          </p>
        </div>
      </div>
      <div class="carousel-item">
        <img class="d-block w-100" src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1555107627/photo-1486406146926-c627a92ad1ab.jpg">
        <div class="carousel-caption">
          <h3>NUESTRA MISION</h3>
          <p>Nuestra Misión es brindar atención personalizada y buscar soluciones adecuadas para los requerimientos de cada uno de nuestros clientes con respecto a sus necesidades de operaciones cambiarias. Nuestros clientes son nuestra prioridad.</p>
        </div>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </section>
  <section id= 'contacto'>
    <div class="contact">
      <h1>COMUNICATE</h1>
      <div class="direccion">
        <div class="direccion-content">
          <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1558564658/Captura_de_Pantalla_2019-05-22_a_la_s_19.36.24.png" class= "logo" alt="">
          <h3> Buenos Aires</h3>
          <p> Av. Callao 1125 - CABA</p>
          <p> <i class="fab fa-whatsapp-square", style= "color:green"></i> +54 (911) 6006-2731</p>
          <a href="mailito:info.lamebo@gmail.com">info.lamebo@gmail.com</a>
          <br><br>
          <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1555105129/Lamebo_0419_Baja-9335.jpg" alt="">
          <h4>HORARIOS</h4>
          <h2> Lunes a Viernes: 8:30 a 17 hs - Sabados y feriados: 9 a 17:00 hs</h2>

        </div>
        <div class="direccion-img">
          <img src="https://res.cloudinary.com/dw7ox75dg/image/upload/v1554910597/Captura_de_Pantalla_2019-04-10_a_la_s_12.35.38.png" alt="">
        </div>
      </div>
    </div>
  </section>

app/views/cambios/show.html.erb
<div class="form-container">
  <h1>Cotizacion</h1>
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Moneda</th>
        <th scope="col"></th>
        <th scope="col">Venta</th>
        <th scope="col">Compra</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td>Dolar</td>
        <td></td>
        <td><%= @cambio.dolarv %></td>
        <td><%= @cambio.dolarc %></td>
      </tr>
      <tr>
        <td>Euros</td>
        <td></td>
        <td><%= @cambio.eurov %></td>
        <td><%= @cambio.euroc %></td>
      </tr>
      <tr>
        <td>Libras</td>
        <td></td>
        <td><%= @cambio.gbpcompra %></td>
        <td><%= @cambio.gbpventa %></td>
      </tr>
      <tr>
        <td>Real</td>
        <td></td>
        <td><%= @cambio.realv %></td>
        <td><%= @cambio.realc %></td>
      </tr>
      <tr>
        <td>Uruguayo</td>
        <td></td>
        <td>$<%= @cambio.uruguayo %></td>
        <td>$<%= @cambio.uruguayov %></td>
      </tr>
      <tr>
        <td>Chileno</td>
        <td></td>
        <td>$<%= @cambio.chilenoc %></td>
        <td>$<%= @cambio.chilenov %></td>
      </tr>
    </tbody>
  </table>
  <div class="text-center">
    <h1><%= link_to 'Editar' , edit_cambio_path , class: "btn btn-primary"%></h1>
    <h1><%= link_to 'Atras', root_path , class: "btn btn-danger"%></h1>
  </div>
  <br><br><br><br>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Lamebo | Agencia de Cambio 20133 - Autorizada por el B.C.R.A | Lamebo</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= render 'shared/footer' %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="http://www.instagram.com" , target= "blank"><i class="fab fa-instagram"></i></a>
    <a href="http://www.facebook.com" , target= "blank"><i class="fab fa-facebook"></i></a>
    <a href="http://www.twitter.com" , target= "blank"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="footer-copyright">
    Made by
    <a href="http://www.guillermo-varela.com " target="_blank">GV-WEB</a>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to root_path, class: "navbar-brand" do %>
    <%= image_tag 'https://res.cloudinary.com/dw7ox75dg/image/upload/v1554905462/74148e0c-ed6f-4f04-973e-b3a4a167e30a.jpg' %>

    <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
         <% if user_signed_in? %>
         <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fas fa-sign-out-alt"></i> <%= t(".sign_out", default: "Log out") %>
              <% end %>
              <% else %>
        <%= link_to "COTIZACION", "#cotizaciones", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "¿QUIENES SOMOS?", "#quienes", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "CONTACTO", "#contacto", class: "nav-link" %>
      </li>
      <li class="nav-item dropdown">
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <%= link_to "Action", "#", class: "dropdown-item" %>
          <%= link_to "Another action", "#", class: "dropdown-item" %>
          <% end %>
        </div>
      </li>
    </ul>
  </div>
</div>